#!/usr/bin/env python3
"""Generate reviewed constants from canonical protocol schemas."""
from __future__ import annotations
import argparse,json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"raspberry-pi/src/aerolink_pi/generated_protocol.py"

def render():
    uart=json.loads((ROOT/"schemas/uart-v1.json").read_text());fleet=json.loads((ROOT/"schemas/fleet-v1.json").read_text())
    return """# Generated by scripts/generate_protocol.py; do not edit.\nUART_VERSION = %r\nUART_MAX_PAYLOAD = %r\nUART_MAX_FRAME = %r\nUART_MESSAGE_TYPES = %r\nFLEET_VERSION = %r\nFLEET_MAX_CANONICAL_BYTES = %r\nFLEET_ALLOWED_KINDS = %r\n"""%(uart["version"],uart["max_payload"],uart["max_frame"],uart["message_types"],fleet["version"],fleet["max_canonical_bytes"],tuple(fleet["allowed_kinds"]))

def main():
    p=argparse.ArgumentParser();p.add_argument("--check",action="store_true");a=p.parse_args();content=render()
    if a.check:
        if not OUT.exists() or OUT.read_text()!=content:raise SystemExit("generated protocol constants are stale")
    else:OUT.write_text(content)

if __name__=="__main__":main()
